name: Publish Backend
on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'


jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: 
        cd backend
        ko build --platform=linux/amd64,linux/arm64
